apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "crane.konveyor.io/v1alpha1",
          "kind": "OperatorConfig",
          "metadata": {
            "name": "openshift-migration"
          },
          "spec": null
        }
      ]
    capabilities: Basic Install
    console.openshift.io/plugins: '["crane-ui-plugin"]'
    operatorframework.io/suggested-namespace: openshift-migration
    operators.operatorframework.io/builder: operator-sdk-v1.14.0+git
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: mtrho-operator.v99.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: OperatorConfig is the Schema for the operatorconfigs API
      displayName: Operator Config
      kind: OperatorConfig
      name: operatorconfigs.crane.konveyor.io
      version: v1alpha1
  description: migration toolkit for Red Hat OpenShift
  displayName: mtRHO
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - console.openshift.io
          resources:
          - consoleplugins
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - crane.konveyor.io
          resources:
          - operatorconfigs
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - crane.konveyor.io
          resources:
          - operatorconfigs/finalizers
          verbs:
          - update
        - apiGroups:
          - crane.konveyor.io
          resources:
          - operatorconfigs/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - tekton.dev
          resources:
          - clustertasks
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        serviceAccountName: mtrho-operator-controller-manager
      - rules:
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - get
        serviceAccountName: proxy
      deployments:
      - name: mtrho-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=10
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources: {}
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                env:
                - name: CRANE_RUNNER_IMAGE
                  value: quay.io/konveyor/crane-runner:latest
                - name: CRANE_UI_PLUGIN_IMAGE
                  value: quay.io/konveyor/crane-ui-plugin:latest
                - name: CRANE_REVERSE_PROXY_IMAGE
                  value: quay.io/konveyor/crane-reverse-proxy:latest
                - name: CRANE_SECRET_SERVICE_IMAGE
                  value: quay.io/konveyor/crane-secret-service:latest
                image: quay.io/konveyor/mtrho-operator:latest
                imagePullPolicy: Always
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
              securityContext:
                runAsNonRoot: true
              serviceAccountName: mtrho-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        - apiGroups:
          - ""
          resources:
          - services
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        serviceAccountName: mtrho-operator-controller-manager
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
        serviceAccountName: proxy
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - mtrho
  - MTRHO
  - crane
  links:
  - name: Mtrho Operator
    url: https://mtrho-operator.domain
  maturity: alpha
  provider:
    name: Red Hat
  relatedImages:
  - image: quay.io/konveyor/crane-runner:latest
    name: crane-runner
  - image: quay.io/konveyor/crane-ui-plugin:latest
    name: crane-ui-plugin
  - image: quay.io/konveyor/crane-secret-service:latest
    name: crane-secret-service
  - image: quay.io/konveyor/crane-reverse-proxy:latest
    name: crane-reverse-proxy
  version: 99.0.0
