---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: proxy
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: proxy
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: proxy
subjects:
  - kind: ServiceAccount
    name: proxy
    namespace: openshift-migration-toolkit
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: proxy
subjects:
  - kind: ServiceAccount
    name: proxy
    namespace: openshift-migration-toolkit
