apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    console.openshift.io/plugins: '["crane-ui-plugin"]'
    operatorframework.io/suggested-namespace: openshift-migration-toolkit
  name: crane-operator.v99.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: OperatorConfig is the Schema for the operatorconfigs API
      displayName: Operator Config
      kind: OperatorConfig
      name: operatorconfigs.crane.konveyor.io
      version: v1alpha1
  description: migration toolkit for Red Hat OpenShift
  displayName: Crane
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - crane
  links:
  - name: Crane Operator
    url: https://crane-operator.domain
  maturity: alpha
  provider:
    name: Red Hat
  relatedImages:
  - image: quay.io/konveyor/crane-runner:latest
    name: crane-runner
  - image: quay.io/konveyor/crane-ui-plugin:latest
    name: crane-ui-plugin
  - image: quay.io/konveyor/crane-secret-service:latest
    name: crane-secret-service
  - image: quay.io/konveyor/crane-reverse-proxy:latest
    name: crane-reverse-proxy
  version: 99.0.0
